name: Deploy and Release

on:
  push:
    tags:
      - "v*"
      # - "[0-9]+.[0-9]+.[0-9]+"
      # - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      # - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      # - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest

    environment:
      name: release

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build twine
          pip install -r requirements.txt

      - name: Build the package
        run: python -m build --no-isolation

      - name: List dist directory
        run: ls -l dist/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*.tar.gz,dist/*.whl
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Check distribution's long description rendering on PyPI
        run: twine check dist/*

      - name: Publish package
        if: github.repository == 'xMohnad/SManga'
        uses: pypa/gh-action-pypi-publish@release/v1
